/// The colors supported by CSS.
public enum NamedColor: String, Color {
  case currentColor = "currentcolor"
  case inherit
  case transparent
  case black
  case silver
  case gray
  case white
  case maroon
  case red
  case purple
  case fuchsia
  case green
  case lime
  case olive
  case yellow
  case navy
  case blue
  case teal
  case aqua
  case orange
  case aliceblue
  case antiquewhite
  case aquamarine
  case azure
  case beige
  case bisque
  case blanchedalmond
  case blueviolet
  case brown
  case burlywood
  case cadetblue
  case chartreuse
  case chocolate
  case coral
  case cornflowerblue
  case cornsilk
  case crimson
  case cyan
  case darkblue
  case darkcyan
  case darkgoldenrod
  case darkgray
  case darkgreen
  case darkgrey
  case darkkhaki
  case darkmagenta
  case darkolivegreen
  case darkorange
  case darkorchid
  case darkred
  case darksalmon
  case darkseagreen
  case darkslateblue
  case darkslategray
  case darkslategrey
  case darkturquoise
  case darkviolet
  case deeppink
  case deepskyblue
  case dimgray
  case dimgrey
  case dodgerblue
  case firebrick
  case floralwhite
  case forestgreen
  case gainsboro
  case ghostwhite
  case gold
  case goldenrod
  case greenyellow
  case grey
  case honeydew
  case hotpink
  case indianred
  case indigo
  case ivory
  case khaki
  case lavender
  case lavenderblush
  case lawngreen
  case lemonchiffon
  case lightblue
  case lightcoral
  case lightcyan
  case lightgoldenrodyellow
  case lightgray
  case lightgreen
  case lightgrey
  case lightpink
  case lightsalmon
  case lightseagreen
  case lightskyblue
  case lightslategray
  case lightslategrey
  case lightsteelblue
  case lightyellow
  case limegreen
  case linen
  case magenta
  case mediumaquamarine
  case mediumblue
  case mediumorchid
  case mediumpurple
  case mediumseagreen
  case mediumslateblue
  case mediumspringgreen
  case mediumturquoise
  case mediumvioletred
  case midnightblue
  case mintcream
  case mistyrose
  case moccasin
  case navajowhite
  case oldlace
  case olivedrab
  case orangered
  case orchid
  case palegoldenrod
  case palegreen
  case paleturquoise
  case palevioletred
  case papayawhip
  case peachpuff
  case peru
  case pink
  case plum
  case powderblue
  case rosybrown
  case royalblue
  case saddlebrown
  case salmon
  case sandybrown
  case seagreen
  case seashell
  case sienna
  case skyblue
  case slateblue
  case slategray
  case slategrey
  case snow
  case springgreen
  case steelblue
  case tan
  case thistle
  case tomato
  case turquoise
  case violet
  case wheat
  case whitesmoke
  case yellowgreen
  case rebeccapurple

  public var className: String {
    render()
  }

  public func render() -> String {
    rawValue
  }
}
